[package]
name = "relative-link-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
scraper = "0.17.1"
url = "2.4.0"
walkdir = "2.3.3"
